version: '3'

services:
  phpfpm:
    image: hipages/php
    environment:
      PHP_FPM_PM_STATUS_PATH: '/status'
    volumes:
      - .:/var/www/html
    networks:
      - integrations

  exporter:
    image: hipages/php-fpm_exporter:latest
    ports:
      - '9253:9253'
    environment:
      PHP_FPM_SCRAPE_URI: 'tcp://phpfpm:9000/status'
      PHP_FPM_LOG_LEVEL: 'debug'
    networks:
      - integrations

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    volumes:
      - ./collector.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - integrations

  nginx:
    image: nginx
    mem_limit: 128m
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpfpm
    networks:
      - integrations

networks:
  integrations:
