receivers:
  memcached:
    endpoint: 'localhost:11211'
    collection_interval: 10s

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [memcached]
      processors: [batch]
      exporters: [logging]
