receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'cockroachdb'
          scrape_interval: 5s
          metrics_path: '/_status/vars'
          scheme: 'http'
          tls_config:
            insecure_skip_verify: true
          static_configs:
            - targets: ['localhost:8080']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging]
