receivers:
  windowsperfcounters:
    collection_interval: 1s
    perfcounters:
      - object: 'Memory'
        counters:
          - name: 'Committed Bytes'
      - object: 'Processor'
        instances: '*'
        counters:
          - name: '% Processor Time'
      - object: 'Processor'
        instances: [1, 2]
        counters:
          - name: '% Idle Time'

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp/lightstep:
    endpoint: ingest.lightstep.com:443
    headers:
      {
        'lightstep-access-token': 'LSKiySqJWrqZoxLh6vkIO/EiXCObybcpaZ8WL8wdE0896jXCconTG11zl3oAUm62SycLYHWrcqjhxSlgx+lDuBm2ARRI8DSYL/6g0Ov9',
      }

service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
      processors: [batch]
      exporters: [logging, otlp/lightstep]
