version: '3.6'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '9989'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'otel:1:1'
    depends_on:
      - zookeeper

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.84.0
    container_name: otel-col
    restart: unless-stopped
    environment:
      LS_ACCESS_TOKEN: ${LS_ACCESS_TOKEN}
    command: ['--config=/etc/otelcol-config.yml']
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-config.yml
    depends_on:
      - kafka
