receivers:
  kafkametrics:
    brokers: kafka:9092
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers

exporters:
  logging:
    loglevel: debug
  # configuring otlp to Lightstep
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      'lightstep-access-token': '${LS_ACCESS_TOKEN}'

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [kafkametrics]
      processors: [batch]
      exporters: [logging, otlp]
