receivers:
  influxdb:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [influxdb]
      processors: [batch]
      exporters: [logging]
